# PART 2 PANDAS

## GROUPBY AND AGGREGATION

In [1]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [4]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [6]:
## GROUP BY CATEGORY AND CALCULATE THE SUM OF SALES

cat = df.groupby('Category')
for i , v in cat:
    print(i)
    print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [8]:
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [9]:
## GROUP BY STORE AND CALCULATE THE SUM OF SALES

cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [13]:
## GROUPBY MULTIPLE COLUMNS
## GROUP BY CATEGORY AND STORE

cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

## AGGREGATION

In [16]:
df['Sales'].mean()

## --> mean median min max count std

np.float64(187.5)

In [17]:
df['Sales'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median'])

## We can give multiple aggregation function by using .agg

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

## PIVOT TABLES

In [18]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

In [21]:
df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    169     25   John  January      Q1
1  2023-01-02       B   West    722     19   Mary  January      Q1
2  2023-01-03       C  North    654     48    Bob  January      Q1
3  2023-01-04       D  South    335     10  Alice  January      Q1
4  2023-01-05       A   East    796     82   John  January      Q1
5  2023-01-06       B   West    581     23   Mary  January      Q1
6  2023-01-07       C  North    520     93    Bob  January      Q1
7  2023-01-08       D  South    238     26  Alice  January      Q1
8  2023-01-09       A   East    491     56   John  January      Q1
9  2023-01-10       B   West    845     52   Mary  January      Q1
10 2023-01-11       C  North    753     86    Bob  January      Q1
11 2023-01-12       D  South    834     89  Alice  January      Q1
12 2023-01-13       A   East    462     34   John  January      Q1
13 2023-01-14       B   West    509     79   Mary  January      Q1
14 2023-01-15       C  North    203     17    Bob  January      Q1
15 2023-01-16       D  South    197     63  Alice  January      Q1
16 2023-01-17       A   East    390     39   John  January      Q1
17 2023-01-18       B   West    908     44   Mary  January      Q1
18 2023-01-19       C  North    771     70    Bob  January      Q1
19 2023-01-20       D  South    273     62  Alice  January      Q1

In [24]:
pd.pivot_table(df,values="Sales",index="Region",columns="Product",aggfunc="median")

Product      A      B      C      D
Region
East     462.0    NaN    NaN    NaN
North      NaN    NaN  654.0    NaN
South      NaN    NaN    NaN  273.0
West       NaN  722.0    NaN    NaN

In [25]:
pivot2 = pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     461.6    NaN    NaN    NaN  47.2   NaN   NaN   NaN
North      NaN    NaN  580.2    NaN   NaN   NaN  62.8   NaN
South      NaN    NaN    NaN  375.4   NaN   NaN   NaN  50.0
West       NaN  713.0    NaN    NaN   NaN  43.4   NaN   NaN

In [28]:
pd.crosstab(df['Region'],df['Product']) ## HERE WE USE COUNTING PURPOSES

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

## OPERATIONS

In [29]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [30]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [31]:
df1.shape

(5, 3)

In [32]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [35]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [36]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [38]:
df1["A"] + 10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

## DATAFRAME APPLYING FUNCTIONS

In [40]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [41]:
def square(x):
    return x**2

In [43]:
df1["B"] = df1["B"].apply(square)

In [44]:
df1

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500

In [ ]:
df1["D"] = df1["B"].apply(square) ## NEW COLUMN CREATED

In [46]:
df1

   A     B    C        D
0  1   100  100    10000
1  2   400  200   160000
2  3   900  300   810000
3  4  1600  400  2560000
4  5  2500  500  6250000

In [47]:
df1['D'] = df1["B"].apply(lambda x : x**2)

In [48]:
df1

   A     B    C        D
0  1   100  100    10000
1  2   400  200   160000
2  3   900  300   810000
3  4  1600  400  2560000
4  5  2500  500  6250000