# PANDAS

## PANDA SERIES

1 D : Labeled Array CAPABLE of Holding any Data Type , The Axis labels are collectively called the Index

In [ ]:
%pip install pandas

In [3]:
### CREATING SERIES 

import numpy as np

import pandas as pd

In [4]:
labels = ['a' , 'b' , 'c']

my_list = [10,20,30]

my_arr = np.array([10,20,30])

d = {1:10,2:20,3:30}

In [5]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [6]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [7]:
pd.Series(my_arr)

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(d) # While creating Series in DICTIONARY WE ARE AUTOMATICALLY DEFINING THE INDEX BY USING KEYS

1    10
2    20
3    30
dtype: int64

## DATAFRAME

In [11]:
### CREATING A DATAFRAME
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df  = pd.DataFrame(data)

In [12]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [28]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

df_2 = pd.DataFrame(data_list)
columns = ["Name" , "Age" , "City" , "Salary"]

In [29]:
df_2 =  pd.DataFrame(data_list,columns = columns)
df_2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### SELECTION AND INDEXING OF COLUMNS

In [30]:
df_2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [31]:
df_2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [32]:
df_2['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: str

In [33]:
df_2[['Name' , 'City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

### CREATING A NEW COLUMNS

In [41]:
df_2["Designation"] = ["Doctor","Engineer","Doctor","Pilot"]

In [42]:
df_2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000       Pilot

In [43]:
df_2.drop("Designation",axis=1,inplace=True) 

## USING INPLACE WILL REMOVE IT COMPLETELY AND PERMANENTLY WITHOUT USING INPLACE WE WILL SEE ITS COPY BEING REMOVES BUT THE DESIGNATION WILL STILL BE THERE IN THE DATAFRAME(IT ONLY SHOWS SNAPSHOT)

In [44]:
df_2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df_2.drop(["City","Salary"],axis=1) ## CITY AND SALARY ARE NOT PERMANENTLY DELETED

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [50]:
df_2.drop(0,axis = 0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [52]:
df_2.drop(1) ## BY DEFAULT AXIS IS 0 ONLY

    Name  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### SELECTING ROWS

In [53]:
df_2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [55]:
df_2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [58]:
df_2.loc[[0,1,2]]

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000

In [59]:
df_2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

### SELECTING SUBSETS OF ROWS AND COLUMNS

In [60]:
df_2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [63]:
df_2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [66]:
df_2.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

### CONDITIONAL SELECTIONS

In [67]:
df_2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [68]:
## SHOW PEOPLE WHOSE AGE IS ABOVE 30 

df_2[df_2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [70]:
### SHOW PEOPLE WHOSE AGE IS ABOVE 30 AND CITY IS PARIS
df_2[(df_2["Age"] > 30) & (df_2["City"] == "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

## MISSING DATA

### Finding Missing DATA

In [71]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df = pd.DataFrame(data)

In [72]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [76]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [77]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [78]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [ ]:
df.dropna() ## ROW WISE SELECTION

     A  B    C    D
0  1.0  1  1.0  1.0

In [81]:
df.dropna(thresh=3) ## THRESH IS USED TO SHOW NON NULL VALUES LIKE IN DF ROW 1 AND 4 HAS MIN 3 NON NULL VALUES SO 0,1,4 ARE DISPLAYED

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

### FILLING THE MISSING DATA

In [82]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [86]:
df.fillna(0) ## TO ACTUALLY APPLY THIS WE NEED TO ALSO USE INPLACE = TRUE

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [ ]:
values = {"A" : 0 , "B":100,"C":300,"D":400 }

df.fillna(value=values) ## COLUMN VISE SELECTION

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [88]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [89]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

## MERGING JOINING AND CONCATENATION

In [90]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [91]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [92]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [95]:
pd.merge(employees,salaries)

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [97]:
pd.merge(employees,salaries,on="employee_id",how="inner")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [99]:
pd.merge(employees,salaries,on="employee_id",how="outer")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [100]:
pd.merge(employees,salaries,on="employee_id",how="right")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [101]:
pd.merge(employees,salaries,on="employee_id",how="left")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

### CONCATENATION OF 2 DATA FRAMES

In [103]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [104]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [105]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [107]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [108]:
pd.concat([df2,df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [109]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

### JOINING OF 2 DATABASE

In [110]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [111]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [112]:
df2

   score
2     85
3     90
4     75

In [113]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [114]:
df1.join(df2,how="outer")

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [115]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

# Pandas: Merge vs Join vs Concat

## Overview

Pandas provides three primary methods to combine DataFrames:

1. `merge()` - SQL-style joins based on columns or indexes.
2. `join()` - Convenient method for joining DataFrames by index.
3. `concat()` - Stacks DataFrames along rows or columns.

---

# 1. merge()

## Purpose

Combine DataFrames using one or more common columns (keys).

### Syntax

```python
pd.merge(
    left,
    right,
    on=None,
    how='inner'
)
```

### Example

```python
import pandas as pd

df1 = pd.DataFrame({
    'id': [1, 2, 3],
    'name': ['A', 'B', 'C']
})

df2 = pd.DataFrame({
    'id': [1, 2, 4],
    'age': [20, 21, 22]
})

result = pd.merge(df1, df2, on='id')
print(result)
```

### Output

```text
   id name  age
0   1    A   20
1   2    B   21
```

## Join Types

### Inner Join

```python
pd.merge(df1, df2, on='id', how='inner')
```

Returns matching records only.

### Left Join

```python
pd.merge(df1, df2, on='id', how='left')
```

Returns all rows from the left DataFrame.

### Right Join

```python
pd.merge(df1, df2, on='id', how='right')
```

Returns all rows from the right DataFrame.

### Outer Join

```python
pd.merge(df1, df2, on='id', how='outer')
```

Returns all rows from both DataFrames.

---

# 2. join()

## Purpose

Join DataFrames primarily using indexes.

### Syntax

```python
df1.join(df2)
```

### Example

```python
df1 = pd.DataFrame({
    'name': ['A', 'B', 'C']
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    'age': [20, 21, 22]
}, index=[1, 2, 4])

result = df1.join(df2)
print(result)
```

### Output

```text
  name   age
1    A  20.0
2    B  21.0
3    C   NaN
```

## Equivalent Merge

```python
df1.merge(
    df2,
    left_index=True,
    right_index=True
)
```

## When to Use

* DataFrames already have meaningful indexes.
* Simpler syntax than `merge()`.
* Quick index-based joins.

---

# 3. concat()

## Purpose

Combine DataFrames by stacking them vertically or horizontally.

---

## Row-wise Concatenation (Default)

### Example

```python
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'A': [3, 4]})

result = pd.concat([df1, df2])
print(result)
```

### Output

```text
   A
0  1
1  2
0  3
1  4
```

### Reset Index

```python
pd.concat([df1, df2], ignore_index=True)
```

Output:

```text
   A
0  1
1  2
2  3
3  4
```

---

## Column-wise Concatenation

### Example

```python
pd.concat([df1, df2], axis=1)
```

### Output

```text
   A  A
0  1  3
1  2  4
```

## When to Use

* Appending datasets.
* Combining monthly reports.
* Stacking rows.
* Combining columns side-by-side.

---

# Comparison Table

| Feature                               | merge() | join()  | concat() |
| ------------------------------------- | ------- | ------- | -------- |
| SQL-style joins                       | ✅       | Limited | ❌        |
| Based on columns                      | ✅       | ❌       | ❌        |
| Based on indexes                      | ✅       | ✅       | ✅        |
| Stack rows                            | ❌       | ❌       | ✅        |
| Stack columns                         | ❌       | ❌       | ✅        |
| Supports inner/left/right/outer joins | ✅       | ✅       | ❌        |
| Most flexible                         | ✅       | ❌       | ❌        |
| Easiest syntax                        | ❌       | ✅       | ✅        |

---

# Interview Cheat Sheet

### Use `merge()`

When matching records using a common key.

```python
pd.merge(customers, orders, on='customer_id')
```

---

### Use `join()`

When matching DataFrames using indexes.

```python
df1.join(df2)
```

---

### Use `concat()`

When stacking DataFrames.

```python
pd.concat([df1, df2])
```

---

# Memory Trick

```text
merge  -> Match records using columns
join   -> Match indexes
concat -> Stack DataFrames
```

---

# Quick Decision Flow

```text
Need SQL-like join?
        |
       Yes
        |
     merge()

Need to join using index?
        |
       Yes
        |
      join()

Need to stack DataFrames?
        |
       Yes
        |
     concat()
```